version: "3.7"

services:
  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - "./client:/home/app"
      - "/home/app/node_modules"
    ports:
      - 8081:8080
    env_file:
      - './client/.env.development'
    depends_on:
      - neo4j_db

  neo4j_db:
    image: neo4j
    ports:
      - 7474:7474
      - 7475:7475
