AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

# Offense count: 1
# Cop supports --auto-correct.
Layout/EmptyLines:
  Exclude:
    - 'Gemfile'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: empty_lines, no_empty_lines
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleAlignWith, AutoCorrect, Severity.
# SupportedStylesAlignWith: keyword, variable, start_of_line
Layout/EndAlignment:
  Exclude:
    - 'app/controllers/users/sessions_controller.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment, ForceEqualSignAlignment.
Layout/ExtraSpacing:
  Exclude:
    - 'config/routes.rb'

# Offense count: 1
# Cop supports --auto-correct.
Layout/SpaceBeforeComma:
  Exclude:
    - 'Gemfile'

# Offense count: 2
# Cop supports --auto-correct.
Lint/UnneededCopDisableDirective:
  Exclude:
    - 'app/controllers/graphql_controller.rb'
    - 'config/initializers/devise.rb'

# Offense count: 1
# Cop supports --auto-correct.
Lint/UnneededCopEnableDirective:
  Exclude:
    - 'config/routes.rb'

# Offense count: 2
Lint/UselessAssignment:
  Exclude:
    - 'db/seeds.rb'
    - 'spec/controllers/user/registrations_controller_spec.rb'

# Offense count: 5
# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Max: 298

# Offense count: 6
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: braces, no_braces, context_dependent
Style/BracesAroundHashParameters:
  Exclude:
    - 'Gemfile'
    - 'app/graphql/types/mutation_type.rb'
    - 'spec/requests/graphql/ping_requests_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, EnforcedStyle.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/users/sessions_controller.rb'

# Offense count: 27
Style/Documentation:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: when_needed, always, never
Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/schema.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, UseHashRocketsWithSymbolValues, PreferHashRocketsForNonAlnumEndingSymbols.
# SupportedStyles: ruby19, hash_rockets, no_mixed_keys, ruby19_no_mixed_keys
Style/HashSyntax:
  Exclude:
    - 'Gemfile'

# Offense count: 2
Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: MinDigits, Strict.
Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

# Offense count: 55
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'Gemfile'
    - 'db/schema.rb'

# Offense count: 128
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 216
