source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.2', '>= 6.0.2.1'
# Use Puma as the app server
gem 'puma', '~> 4.1'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'
gem 'graphql'
# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'
gem 'rubocop-rails'
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
	gem 'solargraph'
	gem 'graphiql-rails'
end

group :test do
	gem 'factory_bot'
  gem 'factory_bot_rails'
  gem 'rspec-rails'
  gem 'ffaker', { git: 'https://github.com/ffaker/ffaker', branch: 'master' }
  gem "fakeredis", "~> 0.7.0", :require => 'fakeredis/rspec'
  gem 'rails-controller-testing'
  gem 'shoulda-matchers'
  gem 'bundler-audit', '~> 0.6.1'
  gem "capybara", "~> 3.26"
	gem "neo4j-rspec"
  gem 'database_cleaner'
  gem 'rspec_junit_formatter', '~> 0.4.1'
end
# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'neo4j', '~> 9.2.0'
